import { useState, useEffect } from 'react';
import Card from '../../components/Card';
import Button from '../../components/Button';
import Input from '../../components/Input';
import { storageService } from '../../services/storage';
import '../../styles/common.css';

interface TruckingSettings {
  defaultRate: number;
  defaultPaymentTerms: number;
  autoGenerateDO: boolean;
  autoGenerateBill: boolean;
  truckingInterval: number;
  notificationEnabled: boolean;
  mapProvider: 'Google Maps' | 'OpenStreetMap';
}

const Settings = () => {
  const [settings, setSettings] = useState<TruckingSettings>({
    defaultRate: 50000,
    defaultPaymentTerms: 30,
    autoGenerateDO: false,
    autoGenerateBill: false,
    truckingInterval: 5,
    notificationEnabled: true,
    mapProvider: 'Google Maps',
  });
  const [saved, setSaved] = useState(false);
  // Custom Dialog state
  const [dialogState, setDialogState] = useState<{
    show: boolean;
    type: 'alert' | 'confirm' | null;
    title: string;
    message: string;
    onConfirm?: () => void;
    onCancel?: () => void;
  }>({
    show: false,
    type: null,
    title: '',
    message: '',
  });

  // Helper functions untuk dialog
  const showAlert = (message: string, title: string = 'Information') => {
    if (typeof window !== 'undefined' && (window as any).setDialogOpen) {
      (window as any).setDialogOpen(true);
    }
    setDialogState({
      show: true,
      type: 'alert',
      title,
      message,
    });
  };

  const showConfirm = (message: string, onConfirm: () => void, onCancel?: () => void, title: string = 'Confirmation') => {
    if (typeof window !== 'undefined' && (window as any).setDialogOpen) {
      (window as any).setDialogOpen(true);
    }
    setDialogState({
      show: true,
      type: 'confirm',
      title,
      message,
      onConfirm,
      onCancel,
    });
  };

  const closeDialog = () => {
    if (typeof window !== 'undefined' && (window as any).setDialogOpen) {
      (window as any).setDialogOpen(false);
    }
    setDialogState({
      show: false,
      type: null,
      title: '',
      message: '',
    });
  };


  useEffect(() => {
    loadSettings();
  }, []);

  const loadSettings = async () => {
    const data = await storageService.get<TruckingSettings>('trucking_settings');
    if (data) {
      setSettings(data);
    }
  };

  const handleSave = async () => {
    try {
      await storageService.set('trucking_settings', settings);
      setSaved(true);
      setTimeout(() => setSaved(false), 3000);
    } catch (error: any) {
      showAlert(`Error saving settings: ${error.message}`, 'Error');
    }
  };

  return (
    <div>
      <div className="page-header">
        <h1>Settings</h1>
      </div>

      <Card title="Trucking Settings">
        <Input
          label="Default Rate (Rp)"
          type="number"
          value={String(settings.defaultRate)}
          onChange={(v) => setSettings({ ...settings, defaultRate: Number(v) })}
        />
        <Input
          label="Default Payment Terms (Days)"
          type="number"
          value={String(settings.defaultPaymentTerms)}
          onChange={(v) => setSettings({ ...settings, defaultPaymentTerms: Number(v) })}
        />
        <Input
          label="Trucking Interval (Seconds)"
          type="number"
          value={String(settings.truckingInterval)}
          onChange={(v) => setSettings({ ...settings, truckingInterval: Number(v) })}
        />
        <div style={{ marginBottom: '16px' }}>
          <label style={{ display: 'block', marginBottom: '8px', color: 'var(--text-primary)', fontWeight: '500' }}>
            Map Provider
          </label>
          <select
            value={settings.mapProvider}
            onChange={(e) => setSettings({ ...settings, mapProvider: e.target.value as any })}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: '1px solid var(--border)',
              borderRadius: '4px',
              backgroundColor: 'var(--bg-primary)',
              color: 'var(--text-primary)',
              fontSize: '14px',
            }}
          >
            <option value="Google Maps">Google Maps</option>
            <option value="OpenStreetMap">OpenStreetMap</option>
          </select>
        </div>
        <div style={{ marginBottom: '16px' }}>
          <label style={{ display: 'flex', alignItems: 'center', gap: '8px', cursor: 'pointer' }}>
            <input
              type="checkbox"
              checked={settings.autoGenerateDO}
              onChange={(e) => setSettings({ ...settings, autoGenerateDO: e.target.checked })}
            />
            <span>Auto-generate Delivery Order</span>
          </label>
        </div>
        <div style={{ marginBottom: '16px' }}>
          <label style={{ display: 'flex', alignItems: 'center', gap: '8px', cursor: 'pointer' }}>
            <input
              type="checkbox"
              checked={settings.autoGenerateBill}
              onChange={(e) => setSettings({ ...settings, autoGenerateBill: e.target.checked })}
            />
            <span>Auto-generate Bill after Delivery</span>
          </label>
        </div>
        <div style={{ marginBottom: '16px' }}>
          <label style={{ display: 'flex', alignItems: 'center', gap: '8px', cursor: 'pointer' }}>
            <input
              type="checkbox"
              checked={settings.notificationEnabled}
              onChange={(e) => setSettings({ ...settings, notificationEnabled: e.target.checked })}
            />
            <span>Enable Notifications</span>
          </label>
        </div>
        <div style={{ display: 'flex', gap: '8px', marginTop: '16px' }}>
          <Button onClick={handleSave} variant="primary">
            Save Settings
          </Button>
          {saved && (
            <span style={{ color: 'var(--success)', display: 'flex', alignItems: 'center' }}>
              ✓ Settings saved!
            </span>
          )}
        </div>
      </Card>
      {/* Custom Dialog */}
      {dialogState.show && (
        <div className="dialog-overlay" onClick={closeDialog}>
          <div onClick={(e) => e.stopPropagation()} style={{ maxWidth: '500px', width: '90%' }}>
            <Card className="dialog-card">
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px' }}>
                <h2>{dialogState.title}</h2>
                <Button variant="secondary" onClick={closeDialog} style={{ padding: '6px 12px' }}>✕</Button>
              </div>
              <p style={{ marginBottom: '20px', whiteSpace: 'pre-wrap' }}>{dialogState.message}</p>
              <div style={{ display: 'flex', gap: '12px', justifyContent: 'flex-end' }}>
                {dialogState.type === 'confirm' && (
                  <Button variant="secondary" onClick={closeDialog}>Cancel</Button>
                )}
                <Button
                  variant="primary"
                  onClick={() => {
                    if (dialogState.onConfirm) dialogState.onConfirm();
                    closeDialog();
                  }}
                >
                  {dialogState.type === 'confirm' ? 'Confirm' : 'OK'}
                </Button>
              </div>
            </Card>
          </div>
        </div>
      )}

    </div>
  );
};

export default Settings;


