// Language service for multi-language support
export type Language = 'id' | 'en';

interface LanguageStrings {
  [key: string]: {
    [key: string]: string;
  };
}

const translations: LanguageStrings = {
  id: {
    // Common
    'common.save': 'Simpan',
    'common.cancel': 'Batal',
    'common.delete': 'Hapus',
    'common.edit': 'Edit',
    'common.add': 'Tambah',
    'common.close': 'Tutup',
    'common.confirm': 'Konfirmasi',
    'common.loading': 'Memuat...',
    'common.error': 'Kesalahan',
    'common.success': 'Berhasil',
    'common.warning': 'Peringatan',
    'common.info': 'Informasi',
    'common.search': 'Cari',
    'common.filter': 'Filter',
    'common.export': 'Ekspor',
    'common.import': 'Impor',
    'common.print': 'Cetak',
    'common.back': 'Kembali',
    'common.next': 'Lanjut',
    'common.previous': 'Sebelumnya',
    'common.yes': 'Ya',
    'common.no': 'Tidak',
    'common.number': 'No.',
    'common.ok': 'OK',
    'common.apply': 'Terapkan',
    'common.reset': 'Reset',
    'common.clear': 'Bersihkan',
    'common.select': 'Pilih',
    'common.all': 'Semua',
    'common.none': 'Tidak ada',
    'common.from': 'Dari',
    'common.to': 'Ke',
    'common.date': 'Tanggal',
    'common.time': 'Waktu',
    'common.status': 'Status',
    'common.action': 'Aksi',
    'common.actions': 'Aksi',
    'common.total': 'Total',
    'common.amount': 'Jumlah',
    'common.price': 'Harga',
    'common.quantity': 'Kuantitas',
    'common.unit': 'Satuan',
    'common.description': 'Deskripsi',
    'common.notes': 'Catatan',
    'common.code': 'Kode',
    'common.name': 'Nama',
    'common.return': 'Pengembalian',
    'common.email': 'Email',
    'common.phone': 'Telepon',
    'common.address': 'Alamat',
    'common.city': 'Kota',
    'common.country': 'Negara',
    'common.zipcode': 'Kode Pos',
    'common.created': 'Dibuat',
    'common.updated': 'Diperbarui',
    'common.createdAt': 'Dibuat pada',
    'common.updatedAt': 'Diperbarui pada',
    'common.createdBy': 'Dibuat oleh',
    'common.updatedBy': 'Diperbarui oleh',

    // Settings
    'settings.title': 'Pengaturan',
    'settings.language': 'Bahasa',
    'settings.languageChanged': 'Bahasa berhasil diubah',
    'settings.theme': 'Tema',
    'settings.appearance': 'Tampilan',
    'settings.company': 'Perusahaan',
    'settings.companyName': 'Nama Perusahaan',
    'settings.companyAddress': 'Alamat Perusahaan',
    'settings.bankName': 'Nama Bank',
    'settings.bankAccount': 'Nomor Rekening',
    'settings.npwp': 'NPWP',
    'settings.buffer': 'Buffer (Rp)',
    'settings.workingCapital': 'Modal Kerja (Rp)',
    'settings.storage': 'Penyimpanan',
    'settings.storageType': 'Tipe Penyimpanan',
    'settings.localStorage': 'Penyimpanan Lokal',
    'settings.serverStorage': 'Server Docker',
    'settings.serverUrl': 'URL Server',
    'settings.checkConnection': 'Periksa Koneksi',
    'settings.connected': '✓ Terhubung',
    'settings.connectionFailed': '✗ Koneksi Gagal',
    'settings.checking': 'Memeriksa...',
    'settings.syncStatus': 'Status Sinkronisasi',
    'settings.idle': '● Idle',
    'settings.syncing': '🔄 Menyinkronkan...',
    'settings.synced': '✓ Tersinkronisasi',
    'settings.syncError': '✗ Kesalahan',
    'settings.update': 'Pembaruan Aplikasi',
    'settings.currentVersion': 'Versi Saat Ini',
    'settings.checkForUpdates': 'Periksa Pembaruan',
    'settings.downloadUpdate': 'Unduh Pembaruan',
    'settings.installUpdate': 'Instal & Restart',
    'settings.updateAvailable': 'Pembaruan Tersedia',
    'settings.noUpdateAvailable': 'Tidak Ada Pembaruan',
    'settings.updateError': 'Kesalahan Pembaruan',
    'settings.downloading': 'Mengunduh...',
    'settings.downloaded': 'Diunduh',
    'settings.saveSettings': 'Simpan Pengaturan',
    'settings.saveCompanyInfo': 'Simpan Info Perusahaan',
    'settings.settingsSaved': 'Pengaturan Tersimpan!',
    'settings.darkTheme': '🌙 Gelap',
    'settings.lightTheme': '☀️ Terang',

    // Packaging Module
    'packaging.title': 'Packaging',
    'packaging.dashboard': 'Dashboard',
    'packaging.salesOrders': 'Pesanan Penjualan',
    'packaging.purchasing': 'Pembelian',
    'packaging.ppic': 'PPIC',
    'packaging.production': 'Produksi',
    'packaging.qaqc': 'QA/QC',
    'packaging.deliveryNote': 'Nota Pengiriman',
    'packaging.finance': 'Keuangan',
    'packaging.invoices': 'Faktur',
    'packaging.payments': 'Pembayaran',
    'packaging.accountsReceivable': 'Piutang Usaha',
    'packaging.accountsPayable': 'Utang Usaha',
    'packaging.taxManagement': 'Manajemen Pajak',
    'packaging.reports': 'Laporan',
    'packaging.settings': 'Pengaturan',
    'packaging.masterData': 'Data Master',
    'packaging.products': 'Produk',
    'packaging.customers': 'Pelanggan',
    'packaging.suppliers': 'Pemasok',
    'packaging.materials': 'Bahan Baku',
    'packaging.inventory': 'Inventaris',

    // General Trading Module
    'generalTrading.title': 'General Trading',
    'generalTrading.dashboard': 'Dashboard',
    'generalTrading.overview': 'Ringkasan',
    'generalTrading.ordersAndSales': 'Pesanan & Penjualan',
    'generalTrading.purchasing': 'Pembelian',
    'generalTrading.workflow': 'Alur Kerja',
    'generalTrading.finance': 'Keuangan',
    'generalTrading.settings': 'Pengaturan',

    // Sales Orders
    'salesOrder.title': 'Pesanan Penjualan',
    'salesOrder.new': 'Pesanan Baru',
    'salesOrder.list': 'Daftar Pesanan',
    'salesOrder.create': 'Buat Pesanan',
    'salesOrder.edit': 'Edit Pesanan',
    'salesOrder.delete': 'Hapus Pesanan',
    'salesOrder.view': 'Lihat Pesanan',
    'salesOrder.number': 'Nomor PO',
    'salesOrder.date': 'Tanggal Pesanan',
    'salesOrder.customer': 'Pelanggan',
    'salesOrder.deliveryDate': 'Tanggal Pengiriman',
    'salesOrder.items': 'Item',
    'salesOrder.status': 'Status',
    'salesOrder.total': 'Total',
    'salesOrder.notes': 'Catatan',
    'salesOrder.confirm': 'Konfirmasi',
    'salesOrder.cancel': 'Batalkan',
    'salesOrder.draft': 'Draft',
    'salesOrder.open': 'Terbuka',
    'salesOrder.confirmed': 'Dikonfirmasi',
    'salesOrder.completed': 'Selesai',
    'salesOrder.cancelled': 'Dibatalkan',

    // Production
    'production.title': 'Produksi',
    'production.spk': 'Surat Perintah Kerja',
    'production.startProduction': 'Mulai Produksi',
    'production.completeProduction': 'Selesaikan Produksi',
    'production.quantity': 'Kuantitas',
    'production.actualQuantity': 'Kuantitas Aktual',
    'production.startTime': 'Waktu Mulai',
    'production.endTime': 'Waktu Selesai',
    'production.inProgress': 'Sedang Berjalan',
    'production.completed': 'Selesai',

    // QA/QC
    'qaqc.title': 'QA/QC',
    'qaqc.inspection': 'Inspeksi',
    'qaqc.pass': 'Lulus',
    'qaqc.fail': 'Gagal',
    'qaqc.approve': 'Setujui',
    'qaqc.reject': 'Tolak',
    'qaqc.reason': 'Alasan',
    'qaqc.notes': 'Catatan',

    // Delivery
    'delivery.title': 'Pengiriman',
    'delivery.deliveryNote': 'Nota Pengiriman',
    'delivery.create': 'Buat Pengiriman',
    'delivery.markDelivered': 'Tandai Terkirim',
    'delivery.actualDate': 'Tanggal Aktual',
    'delivery.driver': 'Pengemudi',
    'delivery.vehicle': 'Kendaraan',
    'delivery.status': 'Status',
    'delivery.pending': 'Tertunda',
    'delivery.inTransit': 'Dalam Perjalanan',
    'delivery.delivered': 'Terkirim',

    // Finance
    'finance.title': 'Keuangan',
    'finance.invoices': 'Faktur',
    'finance.payments': 'Pembayaran',
    'finance.accountsReceivable': 'Piutang Usaha',
    'finance.accountsPayable': 'Utang Usaha',
    'finance.taxManagement': 'Manajemen Pajak',
    'finance.reports': 'Laporan',
    'finance.invoice': 'Faktur',
    'finance.invoiceNumber': 'Nomor Faktur',
    'finance.invoiceDate': 'Tanggal Faktur',
    'finance.dueDate': 'Tanggal Jatuh Tempo',
    'finance.amount': 'Jumlah',
    'finance.paid': 'Dibayar',
    'finance.outstanding': 'Belum Dibayar',
    'finance.overdue': 'Melewati Jatuh Tempo',
    'finance.send': 'Kirim',
    'finance.recordPayment': 'Catat Pembayaran',
    'finance.paymentMethod': 'Metode Pembayaran',
    'finance.cash': 'Tunai',
    'finance.bankTransfer': 'Transfer Bank',
    'finance.check': 'Cek',
    'finance.creditCard': 'Kartu Kredit',
    'finance.reference': 'Referensi',
    'finance.tax': 'Pajak',
    'finance.taxType': 'Tipe Pajak',
    'finance.vat': 'PPN',
    'finance.pph': 'PPh',
    'finance.taxAmount': 'Jumlah Pajak',
    'finance.taxDate': 'Tanggal Pajak',

    // Master Data Keys
    'master.title': 'Data Master',
    'master.products': 'Produk',
    'master.customers': 'Pelanggan',
    'master.suppliers': 'Pemasok',
    'master.materials': 'Bahan Baku',
    'master.inventory': 'Inventaris',
    'master.productCode': 'Kode Produk',
    'master.productName': 'Nama Produk',
    'master.category': 'Kategori',
    'master.unit': 'Satuan',
    'master.price': 'Harga',
    'master.cost': 'Biaya',
    'master.stock': 'Stok',
    'master.reorderLevel': 'Level Pemesanan Ulang',
    'master.customerCode': 'Kode Pelanggan',
    'master.customerName': 'Nama Pelanggan',
    'master.contactPerson': 'Orang Kontak',
    'master.paymentTerms': 'Syarat Pembayaran',
    'master.supplierCode': 'Kode Pemasok',
    'master.supplierName': 'Nama Pemasok',
    'master.materialCode': 'Kode Bahan',
    'master.materialName': 'Nama Bahan',

    // Trucking Module
    'trucking.title': 'Trucking',
    'trucking.vehicles': 'Kendaraan',
    'trucking.drivers': 'Pengemudi',
    'trucking.routes': 'Rute',
    'trucking.deliveryOrders': 'Pesanan Pengiriman',
    'trucking.pettyCash': 'Kas Kecil',
    'trucking.operations': 'Operasi',
    'trucking.accounting': 'Akuntansi',
    'trucking.generalLedger': 'Buku Besar Umum',
    'trucking.costAnalysis': 'Analisis Biaya',
    'trucking.operationalExpenses': 'Biaya Operasional',
    'trucking.coa': 'COA',
  },
  en: {
    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.close': 'Close',
    'common.confirm': 'Confirm',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.warning': 'Warning',
    'common.info': 'Information',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.print': 'Print',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.number': 'No.',
    'common.ok': 'OK',
    'common.apply': 'Apply',
    'common.reset': 'Reset',
    'common.clear': 'Clear',
    'common.select': 'Select',
    'common.all': 'All',
    'common.none': 'None',
    'common.from': 'From',
    'common.to': 'To',
    'common.date': 'Date',
    'common.time': 'Time',
    'common.status': 'Status',
    'common.action': 'Action',
    'common.actions': 'Actions',
    'common.total': 'Total',
    'common.amount': 'Amount',
    'common.price': 'Price',
    'common.quantity': 'Quantity',
    'common.unit': 'Unit',
    'common.description': 'Description',
    'common.notes': 'Notes',
    'common.code': 'Code',
    'common.name': 'Name',
    'common.return': 'Return',
    'common.email': 'Email',
    'common.phone': 'Phone',
    'common.address': 'Address',
    'common.city': 'City',
    'common.country': 'Country',
    'common.zipcode': 'Zip Code',
    'common.created': 'Created',
    'common.updated': 'Updated',
    'common.createdAt': 'Created At',
    'common.updatedAt': 'Updated At',
    'common.createdBy': 'Created By',
    'common.updatedBy': 'Updated By',

    // Settings
    'settings.title': 'Settings',
    'settings.language': 'Language',
    'settings.languageChanged': 'Language changed successfully',
    'settings.theme': 'Theme',
    'settings.appearance': 'Appearance',
    'settings.company': 'Company',
    'settings.companyName': 'Company Name',
    'settings.companyAddress': 'Company Address',
    'settings.bankName': 'Bank Name',
    'settings.bankAccount': 'Bank Account Number',
    'settings.npwp': 'NPWP',
    'settings.buffer': 'Buffer (Rp)',
    'settings.workingCapital': 'Working Capital (Rp)',
    'settings.storage': 'Storage',
    'settings.storageType': 'Storage Type',
    'settings.localStorage': 'Local Storage',
    'settings.serverStorage': 'Docker Server',
    'settings.serverUrl': 'Server URL',
    'settings.checkConnection': 'Check Connection',
    'settings.connected': '✓ Connected',
    'settings.connectionFailed': '✗ Connection Failed',
    'settings.checking': 'Checking...',
    'settings.syncStatus': 'Sync Status',
    'settings.idle': '● Idle',
    'settings.syncing': '🔄 Syncing...',
    'settings.synced': '✓ Synced',
    'settings.syncError': '✗ Error',
    'settings.update': 'Application Update',
    'settings.currentVersion': 'Current Version',
    'settings.checkForUpdates': 'Check for Updates',
    'settings.downloadUpdate': 'Download Update',
    'settings.installUpdate': 'Install & Restart',
    'settings.updateAvailable': 'Update Available',
    'settings.noUpdateAvailable': 'No Update Available',
    'settings.updateError': 'Update Error',
    'settings.downloading': 'Downloading...',
    'settings.downloaded': 'Downloaded',
    'settings.saveSettings': 'Save Settings',
    'settings.saveCompanyInfo': 'Save Company Info',
    'settings.settingsSaved': 'Settings Saved!',
    'settings.darkTheme': '🌙 Dark',
    'settings.lightTheme': '☀️ Light',

    // Packaging Module
    'packaging.title': 'Packaging',
    'packaging.dashboard': 'Dashboard',
    'packaging.salesOrders': 'Sales Orders',
    'packaging.purchasing': 'Purchasing',
    'packaging.ppic': 'PPIC',
    'packaging.production': 'Production',
    'packaging.qaqc': 'QA/QC',
    'packaging.deliveryNote': 'Delivery Note',
    'packaging.finance': 'Finance',
    'packaging.invoices': 'Invoices',
    'packaging.payments': 'Payments',
    'packaging.accountsReceivable': 'Accounts Receivable',
    'packaging.accountsPayable': 'Accounts Payable',
    'packaging.taxManagement': 'Tax Management',
    'packaging.reports': 'Reports',
    'packaging.settings': 'Settings',
    'packaging.masterData': 'Master Data',
    'packaging.products': 'Products',
    'packaging.customers': 'Customers',
    'packaging.suppliers': 'Suppliers',
    'packaging.materials': 'Materials',
    'packaging.inventory': 'Inventory',

    // General Trading Module
    'generalTrading.title': 'General Trading',
    'generalTrading.dashboard': 'Dashboard',
    'generalTrading.overview': 'Overview',
    'generalTrading.ordersAndSales': 'Orders & Sales',
    'generalTrading.purchasing': 'Purchasing',
    'generalTrading.workflow': 'Workflow',
    'generalTrading.finance': 'Finance',
    'generalTrading.settings': 'Settings',

    // Sales Orders
    'salesOrder.title': 'Sales Orders',
    'salesOrder.new': 'New Order',
    'salesOrder.list': 'Order List',
    'salesOrder.create': 'Create Order',
    'salesOrder.edit': 'Edit Order',
    'salesOrder.delete': 'Delete Order',
    'salesOrder.view': 'View Order',
    'salesOrder.number': 'Order Number',
    'salesOrder.date': 'Order Date',
    'salesOrder.customer': 'Customer',
    'salesOrder.deliveryDate': 'Delivery Date',
    'salesOrder.items': 'Items',
    'salesOrder.status': 'Status',
    'salesOrder.total': 'Total',
    'salesOrder.notes': 'Notes',
    'salesOrder.confirm': 'Confirm',
    'salesOrder.cancel': 'Cancel',
    'salesOrder.draft': 'Draft',
    'salesOrder.open': 'Open',
    'salesOrder.confirmed': 'Confirmed',
    'salesOrder.completed': 'Completed',
    'salesOrder.cancelled': 'Cancelled',

    // Production
    'production.title': 'Production',
    'production.spk': 'Work Order',
    'production.startProduction': 'Start Production',
    'production.completeProduction': 'Complete Production',
    'production.quantity': 'Quantity',
    'production.actualQuantity': 'Actual Quantity',
    'production.startTime': 'Start Time',
    'production.endTime': 'End Time',
    'production.inProgress': 'In Progress',
    'production.completed': 'Completed',

    // QA/QC
    'qaqc.title': 'QA/QC',
    'qaqc.inspection': 'Inspection',
    'qaqc.pass': 'Pass',
    'qaqc.fail': 'Fail',
    'qaqc.approve': 'Approve',
    'qaqc.reject': 'Reject',
    'qaqc.reason': 'Reason',
    'qaqc.notes': 'Notes',

    // Delivery
    'delivery.title': 'Delivery',
    'delivery.deliveryNote': 'Delivery Note',
    'delivery.create': 'Create Delivery',
    'delivery.markDelivered': 'Mark Delivered',
    'delivery.actualDate': 'Actual Date',
    'delivery.driver': 'Driver',
    'delivery.vehicle': 'Vehicle',
    'delivery.status': 'Status',
    'delivery.pending': 'Pending',
    'delivery.inTransit': 'In Transit',
    'delivery.delivered': 'Delivered',

    // Finance
    'finance.title': 'Finance',
    'finance.invoices': 'Invoices',
    'finance.payments': 'Payments',
    'finance.accountsReceivable': 'Accounts Receivable',
    'finance.accountsPayable': 'Accounts Payable',
    'finance.taxManagement': 'Tax Management',
    'finance.reports': 'Reports',
    'finance.invoice': 'Invoice',
    'finance.invoiceNumber': 'Invoice Number',
    'finance.invoiceDate': 'Invoice Date',
    'finance.dueDate': 'Due Date',
    'finance.amount': 'Amount',
    'finance.paid': 'Paid',
    'finance.outstanding': 'Outstanding',
    'finance.overdue': 'Overdue',
    'finance.send': 'Send',
    'finance.recordPayment': 'Record Payment',
    'finance.paymentMethod': 'Payment Method',
    'finance.cash': 'Cash',
    'finance.bankTransfer': 'Bank Transfer',
    'finance.check': 'Check',
    'finance.creditCard': 'Credit Card',
    'finance.reference': 'Reference',
    'finance.tax': 'Tax',
    'finance.taxType': 'Tax Type',
    'finance.vat': 'VAT',
    'finance.pph': 'PPh',
    'finance.taxAmount': 'Tax Amount',
    'finance.taxDate': 'Tax Date',

    // Master Data
    'master.title': 'Master Data',
    'master.products': 'Products',
    'master.customers': 'Customers',
    'master.suppliers': 'Suppliers',
    'master.materials': 'Materials',
    'master.inventory': 'Inventory',
    'master.productCode': 'Product Code',
    'master.productName': 'Product Name',
    'master.category': 'Category',
    'master.unit': 'Unit',
    'master.price': 'Price',
    'master.cost': 'Cost',
    'master.stock': 'Stock',
    'master.reorderLevel': 'Reorder Level',
    'master.customerCode': 'Customer Code',
    'master.customerName': 'Customer Name',
    'master.contactPerson': 'Contact Person',
    'master.paymentTerms': 'Payment Terms',
    'master.supplierCode': 'Supplier Code',
    'master.supplierName': 'Supplier Name',
    'master.materialCode': 'Material Code',
    'master.materialName': 'Material Name',

    // Trucking Module
    'trucking.title': 'Trucking',
    'trucking.vehicles': 'Vehicles',
    'trucking.drivers': 'Drivers',
    'trucking.routes': 'Routes',
    'trucking.deliveryOrders': 'Delivery Orders',
    'trucking.pettyCash': 'Petty Cash',
    'trucking.operations': 'Operations',
    'trucking.accounting': 'Accounting',
    'trucking.generalLedger': 'General Ledger',
    'trucking.costAnalysis': 'Cost Analysis',
    'trucking.operationalExpenses': 'Operational Expenses',
    'trucking.coa': 'COA',
  },
};

class LanguageService {
  private currentLanguage: Language = 'id';
  private listeners: Set<(language: Language) => void> = new Set();

  constructor() {
    // Load language from localStorage
    const saved = localStorage.getItem('app_language');
    if (saved === 'en' || saved === 'id') {
      this.currentLanguage = saved;
    } else {
      this.currentLanguage = 'id'; // Default to Indonesian
    }
  }

  setLanguage(language: Language) {
    this.currentLanguage = language;
    localStorage.setItem('app_language', language);
    this.notifyListeners();
  }

  getLanguage(): Language {
    return this.currentLanguage;
  }

  t(key: string, defaultValue?: string): string {
    const lang = translations[this.currentLanguage];
    
    // Try direct key lookup first (flat structure)
    if (lang && key in lang) {
      return lang[key];
    }
    
    // Fallback: try nested lookup (in case structure is nested)
    const keys = key.split('.');
    let value: any = lang;

    for (const k of keys) {
      if (value && typeof value === 'object' && k in value) {
        value = value[k];
      } else {
        return defaultValue || key;
      }
    }

    return typeof value === 'string' ? value : (defaultValue || key);
  }

  subscribe(listener: (language: Language) => void): () => void {
    this.listeners.add(listener);
    return () => {
      this.listeners.delete(listener);
    };
  }

  private notifyListeners() {
    this.listeners.forEach(listener => listener(this.currentLanguage));
  }
}

export const languageService = new LanguageService();
