version: 1.0.6-build.174
files:
  - url: PT.Trima Laksana Jaya Pratama Setup 1.0.6-build.174.exe
    sha512: ''
    size: 78526783
    blockMapSize: 0
path: PT.Trima Laksana Jaya Pratama Setup 1.0.6-build.174.exe
sha512: ''
releaseDate: '2026-04-01T08:13:24.548Z'
